

python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './mutation_models/citeseer_gat/citeseer_gat_' --path_save_config './mutation_models/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './mutation_models/citeseer_gcn/citeseer_gcn_' --path_save_config './mutation_models/citeseer_gcn/citeseer_gcn_' --model_name 'gcn'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './mutation_models/citeseer_graphsage/citeseer_graphsage_' --path_save_config './mutation_models/citeseer_graphsage/citeseer_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './mutation_models/citeseer_tagcn/citeseer_tagcn_' --path_save_config './mutation_models/citeseer_tagcn/citeseer_tagcn_' --model_name 'tagcn'
python get_mutation_models.py --path_x_np './data/cora/x_np.pkl' --path_edge_index './data/cora/edge_index_np.pkl' --path_y './data/cora/y_np.pkl' --path_save_model './mutation_models/cora_gat/cora_gat_' --path_save_config './mutation_models/cora_gat/cora_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/cora/x_np.pkl' --path_edge_index './data/cora/edge_index_np.pkl' --path_y './data/cora/y_np.pkl' --path_save_model './mutation_models/cora_gcn/cora_gcn_' --path_save_config './mutation_models/cora_gcn/cora_gcn_' --model_name 'gcn'
python get_mutation_models.py --path_x_np './data/cora/x_np.pkl' --path_edge_index './data/cora/edge_index_np.pkl' --path_y './data/cora/y_np.pkl' --path_save_model './mutation_models/cora_graphsage/cora_graphsage_' --path_save_config './mutation_models/cora_graphsage/cora_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/cora/x_np.pkl' --path_edge_index './data/cora/edge_index_np.pkl' --path_y './data/cora/y_np.pkl' --path_save_model './mutation_models/cora_tagcn/cora_tagcn_' --path_save_config './mutation_models/cora_tagcn/cora_tagcn_' --model_name 'tagcn'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './mutation_models/lastfm_gat/lastfm_gat_' --path_save_config './mutation_models/lastfm_gat/lastfm_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './mutation_models/lastfm_gcn/lastfm_gcn_' --path_save_config './mutation_models/lastfm_gcn/lastfm_gcn_' --model_name 'gcn'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './mutation_models/lastfm_graphsage/lastfm_graphsage_' --path_save_config './mutation_models/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './mutation_models/lastfm_tagcn/lastfm_tagcn_' --path_save_config './mutation_models/lastfm_tagcn/lastfm_tagcn_' --model_name 'tagcn'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './mutation_models/pubmed_gat/pubmed_gat_' --path_save_config './mutation_models/pubmed_gat/pubmed_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './mutation_models/pubmed_gcn/pubmed_gcn_' --path_save_config './mutation_models/pubmed_gcn/pubmed_gcn_' --model_name 'gcn'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './mutation_models/pubmed_graphsage/pubmed_graphsage_' --path_save_config './mutation_models/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './mutation_models/pubmed_tagcn/pubmed_tagcn_' --path_save_config './mutation_models/pubmed_tagcn/pubmed_tagcn_' --model_name 'tagcn'

