#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=1-23:00:00
#SBATCH --mail-type=end,fail
#SBATCH --mail-user=yinghua.li@uni.lu
#SBATCH -p batch
#SBATCH --mem 100G

python feature_analysis.py --path_model_file './mutation_models/pubmed_gcn' --model_name 'gcn' --target_model_path './target_models/pubmed_gcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl'  --subject_name 'pubmed_gcn' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_gcn' --model_name 'gcn' --target_model_path './target_models/pubmed_gcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_dice.pkl' --subject_name 'pubmed_gcn_dice' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_gcn' --model_name 'gcn' --target_model_path './target_models/pubmed_gcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_nodeembeddingattack_add.pkl' --subject_name 'pubmed_gcn_nodeembeddingattack_add' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_gcn' --model_name 'gcn' --target_model_path './target_models/pubmed_gcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_nodeembeddingattack_remove.pkl' --subject_name 'pubmed_gcn_nodeembeddingattack_remove' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_gcn' --model_name 'gcn' --target_model_path './target_models/pubmed_gcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_randomattack_add.pkl' --subject_name 'pubmed_gcn_randomattack_add' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_gcn' --model_name 'gcn' --target_model_path './target_models/pubmed_gcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_randomattack_flip.pkl' --subject_name 'pubmed_gcn_randomattack_flip' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_gcn' --model_name 'gcn' --target_model_path './target_models/pubmed_gcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_randomattack_remove.pkl' --subject_name 'pubmed_gcn_randomattack_remove' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'

python feature_analysis.py --path_model_file './mutation_models/pubmed_gat' --model_name 'gat' --target_model_path './target_models/pubmed_gat.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl'  --subject_name 'pubmed_gat' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_gat' --model_name 'gat' --target_model_path './target_models/pubmed_gat.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_dice.pkl' --subject_name 'pubmed_gat_dice' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_gat' --model_name 'gat' --target_model_path './target_models/pubmed_gat.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_nodeembeddingattack_add.pkl' --subject_name 'pubmed_gat_nodeembeddingattack_add' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_gat' --model_name 'gat' --target_model_path './target_models/pubmed_gat.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_nodeembeddingattack_remove.pkl' --subject_name 'pubmed_gat_nodeembeddingattack_remove' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_gat' --model_name 'gat' --target_model_path './target_models/pubmed_gat.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_randomattack_add.pkl' --subject_name 'pubmed_gat_randomattack_add' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_gat' --model_name 'gat' --target_model_path './target_models/pubmed_gat.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_randomattack_flip.pkl' --subject_name 'pubmed_gat_randomattack_flip' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_gat' --model_name 'gat' --target_model_path './target_models/pubmed_gat.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_randomattack_remove.pkl' --subject_name 'pubmed_gat_randomattack_remove' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'

python feature_analysis.py --path_model_file './mutation_models/pubmed_tagcn' --model_name 'tagcn' --target_model_path './target_models/pubmed_tagcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl'  --subject_name 'pubmed_tagcn' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_tagcn' --model_name 'tagcn' --target_model_path './target_models/pubmed_tagcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_dice.pkl' --subject_name 'pubmed_tagcn_dice' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_tagcn' --model_name 'tagcn' --target_model_path './target_models/pubmed_tagcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_nodeembeddingattack_add.pkl' --subject_name 'pubmed_tagcn_nodeembeddingattack_add' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_tagcn' --model_name 'tagcn' --target_model_path './target_models/pubmed_tagcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_nodeembeddingattack_remove.pkl' --subject_name 'pubmed_tagcn_nodeembeddingattack_remove' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_tagcn' --model_name 'tagcn' --target_model_path './target_models/pubmed_tagcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_randomattack_add.pkl' --subject_name 'pubmed_tagcn_randomattack_add' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_tagcn' --model_name 'tagcn' --target_model_path './target_models/pubmed_tagcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_randomattack_flip.pkl' --subject_name 'pubmed_tagcn_randomattack_flip' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_tagcn' --model_name 'tagcn' --target_model_path './target_models/pubmed_tagcn.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_randomattack_remove.pkl' --subject_name 'pubmed_tagcn_randomattack_remove' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'

python feature_analysis.py --path_model_file './mutation_models/pubmed_graphsage' --model_name 'graphsage' --target_model_path './target_models/pubmed_graphsage.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl'  --subject_name 'pubmed_graphsage' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_graphsage' --model_name 'graphsage' --target_model_path './target_models/pubmed_graphsage.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_dice.pkl' --subject_name 'pubmed_graphsage_dice' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_graphsage' --model_name 'graphsage' --target_model_path './target_models/pubmed_graphsage.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_nodeembeddingattack_add.pkl' --subject_name 'pubmed_graphsage_nodeembeddingattack_add' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_graphsage' --model_name 'graphsage' --target_model_path './target_models/pubmed_graphsage.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_nodeembeddingattack_remove.pkl' --subject_name 'pubmed_graphsage_nodeembeddingattack_remove' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_graphsage' --model_name 'graphsage' --target_model_path './target_models/pubmed_graphsage.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_randomattack_add.pkl' --subject_name 'pubmed_graphsage_randomattack_add' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_graphsage' --model_name 'graphsage' --target_model_path './target_models/pubmed_graphsage.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_randomattack_flip.pkl' --subject_name 'pubmed_graphsage_randomattack_flip' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/pubmed_graphsage' --model_name 'graphsage' --target_model_path './target_models/pubmed_graphsage.pt' --path_x_np './data/pubmed/x_np.pkl' --path_edge_index  './data/attack_data/pubmed/pubmed_randomattack_remove.pkl' --subject_name 'pubmed_graphsage_randomattack_remove' --path_y './data/pubmed/y_np.pkl' --path_mutation_edge_index_np_list './data/pubmed/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/pubmed/mutation_x_np_list.pkl'








