#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=1-23:00:00
#SBATCH --mail-type=end,fail
#SBATCH --mail-user=yinghua.li@uni.lu
#SBATCH -p batch
#SBATCH --mem 100G

python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_1/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_1/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_2/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_2/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_3/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_3/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_4/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_4/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_5/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_5/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_6/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_6/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_7/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_7/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_8/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_8/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_9/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_9/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_10/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_10/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_11/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_11/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_12/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_12/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_13/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_13/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_14/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_14/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_15/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_15/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_16/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_16/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_17/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_17/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_18/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_18/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_19/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_19/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/pubmed/x_np.pkl' --path_edge_index './data/pubmed/edge_index_np.pkl' --path_y './data/pubmed/y_np.pkl' --path_save_model './new_mutation_models/repeat_20/pubmed_graphsage/pubmed_graphsage_' --path_save_config './new_mutation_models/repeat_20/pubmed_graphsage/pubmed_graphsage_' --model_name 'graphsage'


