#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=1-23:00:00
#SBATCH --mail-type=end,fail
#SBATCH --mail-user=yinghua.li@uni.lu
#SBATCH -p batch
#SBATCH --mem 100G

python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_1/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_1/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_2/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_2/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_3/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_3/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_4/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_4/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_5/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_5/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_6/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_6/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_7/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_7/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_8/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_8/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_9/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_9/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_10/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_10/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_11/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_11/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_12/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_12/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_13/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_13/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_14/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_14/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_15/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_15/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_16/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_16/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_17/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_17/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_18/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_18/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_19/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_19/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'
python get_mutation_models.py --path_x_np './data/lastfm/x_np.pkl' --path_edge_index './data/lastfm/edge_index_np.pkl' --path_y './data/lastfm/y_np.pkl' --path_save_model './new_mutation_models/repeat_20/lastfm_graphsage/lastfm_graphsage_' --path_save_config './new_mutation_models/repeat_20/lastfm_graphsage/lastfm_graphsage_' --model_name 'graphsage'


