#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=1-23:00:00
#SBATCH --mail-type=end,fail
#SBATCH --mail-user=yinghua.li@uni.lu
#SBATCH -p batch
#SBATCH --mem 100G

python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_1/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_1/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_2/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_2/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_3/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_3/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_4/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_4/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_5/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_5/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_6/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_6/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_7/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_7/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_8/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_8/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_9/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_9/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_10/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_10/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_11/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_11/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_12/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_12/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_13/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_13/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_14/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_14/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_15/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_15/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_16/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_16/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_17/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_17/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_18/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_18/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_19/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_19/citeseer_gat/citeseer_gat_' --model_name 'gat'
python get_mutation_models.py --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl' --path_y './data/citeseer/y_np.pkl' --path_save_model './new_mutation_models/repeat_20/citeseer_gat/citeseer_gat_' --path_save_config './new_mutation_models/repeat_20/citeseer_gat/citeseer_gat_' --model_name 'gat'


