#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=1-23:00:00
#SBATCH --mail-type=end,fail
#SBATCH --mail-user=yinghua.li@uni.lu
#SBATCH -p batch
#SBATCH --mem 100G

python feature_analysis.py --path_model_file './mutation_models/cora_gcn' --model_name 'gcn' --target_model_path './target_models/cora_gcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index './data/cora/edge_index_np.pkl'  --subject_name 'cora_gcn' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gcn' --model_name 'gcn' --target_model_path './target_models/cora_gcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_dice.pkl' --subject_name 'cora_gcn_dice' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gcn' --model_name 'gcn' --target_model_path './target_models/cora_gcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_minmax.pkl' --subject_name 'cora_gcn_minmax' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gcn' --model_name 'gcn' --target_model_path './target_models/cora_gcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_nodeembeddingattack_add.pkl' --subject_name 'cora_gcn_nodeembeddingattack_add' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gcn' --model_name 'gcn' --target_model_path './target_models/cora_gcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_nodeembeddingattack_remove.pkl' --subject_name 'cora_gcn_nodeembeddingattack_remove' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gcn' --model_name 'gcn' --target_model_path './target_models/cora_gcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_pgdattack.pkl' --subject_name 'cora_gcn_pgdattack' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gcn' --model_name 'gcn' --target_model_path './target_models/cora_gcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_randomattack_add.pkl' --subject_name 'cora_gcn_randomattack_add' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gcn' --model_name 'gcn' --target_model_path './target_models/cora_gcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_randomattack_flip.pkl' --subject_name 'cora_gcn_randomattack_flip' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gcn' --model_name 'gcn' --target_model_path './target_models/cora_gcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_randomattack_remove.pkl' --subject_name 'cora_gcn_randomattack_remove' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'


python feature_analysis.py --path_model_file './mutation_models/cora_gat' --model_name 'gat' --target_model_path './target_models/cora_gat.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index './data/cora/edge_index_np.pkl'  --subject_name 'cora_gat' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gat' --model_name 'gat' --target_model_path './target_models/cora_gat.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_dice.pkl' --subject_name 'cora_gat_dice' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gat' --model_name 'gat' --target_model_path './target_models/cora_gat.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_minmax.pkl' --subject_name 'cora_gat_minmax' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gat' --model_name 'gat' --target_model_path './target_models/cora_gat.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_nodeembeddingattack_add.pkl' --subject_name 'cora_gat_nodeembeddingattack_add' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gat' --model_name 'gat' --target_model_path './target_models/cora_gat.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_nodeembeddingattack_remove.pkl' --subject_name 'cora_gat_nodeembeddingattack_remove' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gat' --model_name 'gat' --target_model_path './target_models/cora_gat.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_pgdattack.pkl' --subject_name 'cora_gat_pgdattack' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gat' --model_name 'gat' --target_model_path './target_models/cora_gat.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_randomattack_add.pkl' --subject_name 'cora_gat_randomattack_add' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gat' --model_name 'gat' --target_model_path './target_models/cora_gat.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_randomattack_flip.pkl' --subject_name 'cora_gat_randomattack_flip' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_gat' --model_name 'gat' --target_model_path './target_models/cora_gat.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_randomattack_remove.pkl' --subject_name 'cora_gat_randomattack_remove' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'

python feature_analysis.py --path_model_file './mutation_models/cora_tagcn' --model_name 'tagcn' --target_model_path './target_models/cora_tagcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index './data/cora/edge_index_np.pkl'  --subject_name 'cora_tagcn' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_tagcn' --model_name 'tagcn' --target_model_path './target_models/cora_tagcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_dice.pkl' --subject_name 'cora_tagcn_dice' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_tagcn' --model_name 'tagcn' --target_model_path './target_models/cora_tagcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_minmax.pkl' --subject_name 'cora_tagcn_minmax' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_tagcn' --model_name 'tagcn' --target_model_path './target_models/cora_tagcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_nodeembeddingattack_add.pkl' --subject_name 'cora_tagcn_nodeembeddingattack_add' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_tagcn' --model_name 'tagcn' --target_model_path './target_models/cora_tagcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_nodeembeddingattack_remove.pkl' --subject_name 'cora_tagcn_nodeembeddingattack_remove' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_tagcn' --model_name 'tagcn' --target_model_path './target_models/cora_tagcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_pgdattack.pkl' --subject_name 'cora_tagcn_pgdattack' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_tagcn' --model_name 'tagcn' --target_model_path './target_models/cora_tagcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_randomattack_add.pkl' --subject_name 'cora_tagcn_randomattack_add' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_tagcn' --model_name 'tagcn' --target_model_path './target_models/cora_tagcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_randomattack_flip.pkl' --subject_name 'cora_tagcn_randomattack_flip' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_tagcn' --model_name 'tagcn' --target_model_path './target_models/cora_tagcn.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_randomattack_remove.pkl' --subject_name 'cora_tagcn_randomattack_remove' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'

python feature_analysis.py --path_model_file './mutation_models/cora_graphsage' --model_name 'graphsage' --target_model_path './target_models/cora_graphsage.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index './data/cora/edge_index_np.pkl'  --subject_name 'cora_graphsage' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_graphsage' --model_name 'graphsage' --target_model_path './target_models/cora_graphsage.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_dice.pkl' --subject_name 'cora_graphsage_dice' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_graphsage' --model_name 'graphsage' --target_model_path './target_models/cora_graphsage.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_minmax.pkl' --subject_name 'cora_graphsage_minmax' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_graphsage' --model_name 'graphsage' --target_model_path './target_models/cora_graphsage.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_nodeembeddingattack_add.pkl' --subject_name 'cora_graphsage_nodeembeddingattack_add' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_graphsage' --model_name 'graphsage' --target_model_path './target_models/cora_graphsage.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_nodeembeddingattack_remove.pkl' --subject_name 'cora_graphsage_nodeembeddingattack_remove' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_graphsage' --model_name 'graphsage' --target_model_path './target_models/cora_graphsage.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_pgdattack.pkl' --subject_name 'cora_graphsage_pgdattack' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_graphsage' --model_name 'graphsage' --target_model_path './target_models/cora_graphsage.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_randomattack_add.pkl' --subject_name 'cora_graphsage_randomattack_add' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_graphsage' --model_name 'graphsage' --target_model_path './target_models/cora_graphsage.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_randomattack_flip.pkl' --subject_name 'cora_graphsage_randomattack_flip' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'
python feature_analysis.py --path_model_file './mutation_models/cora_graphsage' --model_name 'graphsage' --target_model_path './target_models/cora_graphsage.pt' --path_x_np './data/cora/x_np.pkl' --path_edge_index  './data/attack_data/cora/cora_randomattack_remove.pkl' --subject_name 'cora_graphsage_randomattack_remove' --path_y './data/cora/y_np.pkl' --path_mutation_edge_index_np_list './data/cora/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/cora/mutation_x_np_list.pkl'








