#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=1-23:00:00
#SBATCH --mail-type=end,fail
#SBATCH --mail-user=yinghua.li@uni.lu
#SBATCH -p batch
#SBATCH --mem 100G

python analysis_parameter_mutationmodels.py --save_name 'hidden5' --path_model_file './paramete_mutation_models/citeseer_gcn' --model_name 'gcn' --target_model_path './target_models/citeseer_gcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'hidden5' --path_model_file './paramete_mutation_models/citeseer_gat' --model_name 'gat' --target_model_path './target_models/citeseer_gat.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gat' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'hidden5' --path_model_file './paramete_mutation_models/citeseer_tagcn' --model_name 'tagcn' --target_model_path './target_models/citeseer_tagcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_tagcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'hidden5' --path_model_file './paramete_mutation_models/citeseer_graphsage' --model_name 'graphsage' --target_model_path './target_models/citeseer_graphsage.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_graphsage' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'

python analysis_parameter_mutationmodels.py --save_name 'hidden10' --path_model_file './paramete_mutation_models/citeseer_gcn' --model_name 'gcn' --target_model_path './target_models/citeseer_gcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'hidden10' --path_model_file './paramete_mutation_models/citeseer_gat' --model_name 'gat' --target_model_path './target_models/citeseer_gat.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gat' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'hidden10' --path_model_file './paramete_mutation_models/citeseer_tagcn' --model_name 'tagcn' --target_model_path './target_models/citeseer_tagcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_tagcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'hidden10' --path_model_file './paramete_mutation_models/citeseer_graphsage' --model_name 'graphsage' --target_model_path './target_models/citeseer_graphsage.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_graphsage' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'

python analysis_parameter_mutationmodels.py --save_name 'hidden15' --path_model_file './paramete_mutation_models/citeseer_gcn' --model_name 'gcn' --target_model_path './target_models/citeseer_gcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'hidden15' --path_model_file './paramete_mutation_models/citeseer_gat' --model_name 'gat' --target_model_path './target_models/citeseer_gat.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gat' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'hidden15' --path_model_file './paramete_mutation_models/citeseer_tagcn' --model_name 'tagcn' --target_model_path './target_models/citeseer_tagcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_tagcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'hidden15' --path_model_file './paramete_mutation_models/citeseer_graphsage' --model_name 'graphsage' --target_model_path './target_models/citeseer_graphsage.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_graphsage' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'

python analysis_parameter_mutationmodels.py --save_name 'hidden20' --path_model_file './paramete_mutation_models/citeseer_gcn' --model_name 'gcn' --target_model_path './target_models/citeseer_gcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'hidden20' --path_model_file './paramete_mutation_models/citeseer_gat' --model_name 'gat' --target_model_path './target_models/citeseer_gat.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gat' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'hidden20' --path_model_file './paramete_mutation_models/citeseer_tagcn' --model_name 'tagcn' --target_model_path './target_models/citeseer_tagcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_tagcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'hidden20' --path_model_file './paramete_mutation_models/citeseer_graphsage' --model_name 'graphsage' --target_model_path './target_models/citeseer_graphsage.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_graphsage' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'


python analysis_parameter_mutationmodels.py --save_name 'heads2' --path_model_file './paramete_mutation_models/citeseer_gcn' --model_name 'gcn' --target_model_path './target_models/citeseer_gcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'heads2' --path_model_file './paramete_mutation_models/citeseer_gat' --model_name 'gat' --target_model_path './target_models/citeseer_gat.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gat' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'heads2' --path_model_file './paramete_mutation_models/citeseer_tagcn' --model_name 'tagcn' --target_model_path './target_models/citeseer_tagcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_tagcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'heads2' --path_model_file './paramete_mutation_models/citeseer_graphsage' --model_name 'graphsage' --target_model_path './target_models/citeseer_graphsage.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_graphsage' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'

python analysis_parameter_mutationmodels.py --save_name 'heads4' --path_model_file './paramete_mutation_models/citeseer_gcn' --model_name 'gcn' --target_model_path './target_models/citeseer_gcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'heads4' --path_model_file './paramete_mutation_models/citeseer_gat' --model_name 'gat' --target_model_path './target_models/citeseer_gat.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gat' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'heads4' --path_model_file './paramete_mutation_models/citeseer_tagcn' --model_name 'tagcn' --target_model_path './target_models/citeseer_tagcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_tagcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'heads4' --path_model_file './paramete_mutation_models/citeseer_graphsage' --model_name 'graphsage' --target_model_path './target_models/citeseer_graphsage.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_graphsage' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'

python analysis_parameter_mutationmodels.py --save_name 'heads6' --path_model_file './paramete_mutation_models/citeseer_gcn' --model_name 'gcn' --target_model_path './target_models/citeseer_gcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'heads6' --path_model_file './paramete_mutation_models/citeseer_gat' --model_name 'gat' --target_model_path './target_models/citeseer_gat.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gat' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'heads6' --path_model_file './paramete_mutation_models/citeseer_tagcn' --model_name 'tagcn' --target_model_path './target_models/citeseer_tagcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_tagcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'heads6' --path_model_file './paramete_mutation_models/citeseer_graphsage' --model_name 'graphsage' --target_model_path './target_models/citeseer_graphsage.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_graphsage' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'

python analysis_parameter_mutationmodels.py --save_name 'heads8' --path_model_file './paramete_mutation_models/citeseer_gcn' --model_name 'gcn' --target_model_path './target_models/citeseer_gcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'heads8' --path_model_file './paramete_mutation_models/citeseer_gat' --model_name 'gat' --target_model_path './target_models/citeseer_gat.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gat' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'heads8' --path_model_file './paramete_mutation_models/citeseer_tagcn' --model_name 'tagcn' --target_model_path './target_models/citeseer_tagcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_tagcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'heads8' --path_model_file './paramete_mutation_models/citeseer_graphsage' --model_name 'graphsage' --target_model_path './target_models/citeseer_graphsage.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_graphsage' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'

python analysis_parameter_mutationmodels.py --save_name 'slope01' --path_model_file './paramete_mutation_models/citeseer_gcn' --model_name 'gcn' --target_model_path './target_models/citeseer_gcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'slope01' --path_model_file './paramete_mutation_models/citeseer_gat' --model_name 'gat' --target_model_path './target_models/citeseer_gat.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gat' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'slope01' --path_model_file './paramete_mutation_models/citeseer_tagcn' --model_name 'tagcn' --target_model_path './target_models/citeseer_tagcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_tagcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'slope01' --path_model_file './paramete_mutation_models/citeseer_graphsage' --model_name 'graphsage' --target_model_path './target_models/citeseer_graphsage.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_graphsage' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'

python analysis_parameter_mutationmodels.py --save_name 'slope02' --path_model_file './paramete_mutation_models/citeseer_gcn' --model_name 'gcn' --target_model_path './target_models/citeseer_gcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'slope02' --path_model_file './paramete_mutation_models/citeseer_gat' --model_name 'gat' --target_model_path './target_models/citeseer_gat.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gat' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'slope02' --path_model_file './paramete_mutation_models/citeseer_tagcn' --model_name 'tagcn' --target_model_path './target_models/citeseer_tagcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_tagcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'slope02' --path_model_file './paramete_mutation_models/citeseer_graphsage' --model_name 'graphsage' --target_model_path './target_models/citeseer_graphsage.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_graphsage' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'

python analysis_parameter_mutationmodels.py --save_name 'slope03' --path_model_file './paramete_mutation_models/citeseer_gcn' --model_name 'gcn' --target_model_path './target_models/citeseer_gcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'slope03' --path_model_file './paramete_mutation_models/citeseer_gat' --model_name 'gat' --target_model_path './target_models/citeseer_gat.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gat' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'slope03' --path_model_file './paramete_mutation_models/citeseer_tagcn' --model_name 'tagcn' --target_model_path './target_models/citeseer_tagcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_tagcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'slope03' --path_model_file './paramete_mutation_models/citeseer_graphsage' --model_name 'graphsage' --target_model_path './target_models/citeseer_graphsage.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_graphsage' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'

python analysis_parameter_mutationmodels.py --save_name 'slope04' --path_model_file './paramete_mutation_models/citeseer_gcn' --model_name 'gcn' --target_model_path './target_models/citeseer_gcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'slope04' --path_model_file './paramete_mutation_models/citeseer_gat' --model_name 'gat' --target_model_path './target_models/citeseer_gat.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_gat' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'slope04' --path_model_file './paramete_mutation_models/citeseer_tagcn' --model_name 'tagcn' --target_model_path './target_models/citeseer_tagcn.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_tagcn' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'
python analysis_parameter_mutationmodels.py --save_name 'slope04' --path_model_file './paramete_mutation_models/citeseer_graphsage' --model_name 'graphsage' --target_model_path './target_models/citeseer_graphsage.pt' --path_x_np './data/citeseer/x_np.pkl' --path_edge_index './data/citeseer/edge_index_np.pkl'  --subject_name 'citeseer_graphsage' --path_y './data/citeseer/y_np.pkl' --path_mutation_edge_index_np_list './data/citeseer/mutation_edge_index_np_list.pkl' --path_mutation_x_np_list './data/citeseer/mutation_x_np_list.pkl'


